#!/bin/bash

echo "=============================="
echo "   Simple Git Command Guide   "
echo "=============================="
echo ""
echo "1. git init                -> Initialize repo"
echo "2. git clone <url>         -> Clone repo"
echo "3. git status              -> Check status"
echo "4. git add .               -> Stage changes"
echo "5. git commit -m 'msg'     -> Commit changes"
echo "6. git push origin main    -> Push to remote"
echo "7. git pull origin main    -> Pull from remote"
echo "8. git branch              -> List branches"
echo "9. git checkout -b <name>  -> Create + switch branch"
echo "10. git merge <branch>     -> Merge branch"
echo "11. git log --oneline      -> Commit history"
echo "12. git diff               -> Show changes"
echo "13. git reset --hard <id>  -> Reset to commit (⚠)"
echo "14. git stash / stash pop  -> Save/restore changes"
echo ""
echo "=============================="
echo "   End of Git Cheat Sheet   "
echo "=============================="
